// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcFGt7ZMVktxWFr5d9isw_AfsU4gttJfI',
    appId: '1:1096246907540:web:dfc790356582ae20b29a81',
    messagingSenderId: '1096246907540',
    projectId: 'notificaciones-push-4f038',
    authDomain: 'notificaciones-push-4f038.firebaseapp.com',
    storageBucket: 'notificaciones-push-4f038.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrenzMJ6pBhWNiChaBu6dVg5k7G01YZKU',
    appId: '1:1096246907540:android:999ffa56e2105459b29a81',
    messagingSenderId: '1096246907540',
    projectId: 'notificaciones-push-4f038',
    storageBucket: 'notificaciones-push-4f038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU4K01Cstl51o2y4KzprVIbrH4QTNg434',
    appId: '1:1096246907540:ios:1bcc888b130edb7fb29a81',
    messagingSenderId: '1096246907540',
    projectId: 'notificaciones-push-4f038',
    storageBucket: 'notificaciones-push-4f038.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU4K01Cstl51o2y4KzprVIbrH4QTNg434',
    appId: '1:1096246907540:ios:1bcc888b130edb7fb29a81',
    messagingSenderId: '1096246907540',
    projectId: 'notificaciones-push-4f038',
    storageBucket: 'notificaciones-push-4f038.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcFGt7ZMVktxWFr5d9isw_AfsU4gttJfI',
    appId: '1:1096246907540:web:043b19c5010b35b1b29a81',
    messagingSenderId: '1096246907540',
    projectId: 'notificaciones-push-4f038',
    authDomain: 'notificaciones-push-4f038.firebaseapp.com',
    storageBucket: 'notificaciones-push-4f038.firebasestorage.app',
  );

}