// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FF0yjn8YPyEx15iUNzvExLqhMWizI94',
    appId: '1:224412285061:web:f68ad90c45293f723291ec',
    messagingSenderId: '224412285061',
    projectId: 'test-login-376e7',
    authDomain: 'test-login-376e7.firebaseapp.com',
    storageBucket: 'test-login-376e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFMaD5hzFIhor_I9THgo17LFbBulagkjw',
    appId: '1:224412285061:android:db77b88b41e36eaa3291ec',
    messagingSenderId: '224412285061',
    projectId: 'test-login-376e7',
    storageBucket: 'test-login-376e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFTsuggjnydpzeeKf4jB0YWYgiL25mJb8',
    appId: '1:224412285061:ios:7eaf772ea8f073c83291ec',
    messagingSenderId: '224412285061',
    projectId: 'test-login-376e7',
    storageBucket: 'test-login-376e7.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFTsuggjnydpzeeKf4jB0YWYgiL25mJb8',
    appId: '1:224412285061:ios:7eaf772ea8f073c83291ec',
    messagingSenderId: '224412285061',
    projectId: 'test-login-376e7',
    storageBucket: 'test-login-376e7.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3FF0yjn8YPyEx15iUNzvExLqhMWizI94',
    appId: '1:224412285061:web:12efea105c492feb3291ec',
    messagingSenderId: '224412285061',
    projectId: 'test-login-376e7',
    authDomain: 'test-login-376e7.firebaseapp.com',
    storageBucket: 'test-login-376e7.firebasestorage.app',
  );

}