// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXASNHDbhpMQLUbcyb1lVaj2lZhgX2rk',
    appId: '1:611820996568:web:52d8b08fe934dde5f494ad',
    messagingSenderId: '611820996568',
    projectId: 'fir-4c-21c06',
    authDomain: 'fir-4c-21c06.firebaseapp.com',
    databaseURL: 'https://fir-4c-21c06-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4c-21c06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQeUWbjdTzPQQN4J0oThgYJaXFL_dW8Hs',
    appId: '1:611820996568:android:207fb96ce0f1023df494ad',
    messagingSenderId: '611820996568',
    projectId: 'fir-4c-21c06',
    databaseURL: 'https://fir-4c-21c06-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4c-21c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7edfy9uADBaRV-_jQ5Hg_mibzj_OdvU',
    appId: '1:611820996568:ios:1f098962076dbd6ef494ad',
    messagingSenderId: '611820996568',
    projectId: 'fir-4c-21c06',
    databaseURL: 'https://fir-4c-21c06-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4c-21c06.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX7edfy9uADBaRV-_jQ5Hg_mibzj_OdvU',
    appId: '1:611820996568:ios:1f098962076dbd6ef494ad',
    messagingSenderId: '611820996568',
    projectId: 'fir-4c-21c06',
    databaseURL: 'https://fir-4c-21c06-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4c-21c06.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxXASNHDbhpMQLUbcyb1lVaj2lZhgX2rk',
    appId: '1:611820996568:web:78f99d0dcaa9f009f494ad',
    messagingSenderId: '611820996568',
    projectId: 'fir-4c-21c06',
    authDomain: 'fir-4c-21c06.firebaseapp.com',
    databaseURL: 'https://fir-4c-21c06-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4c-21c06.firebasestorage.app',
  );
}
